import { NextResponse } from "next/server";
import getCurrentUser from "@/app/action/getCurrentUser";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import prisma from "@/lib/prismadb";

export async function POST(request: Request) {
  const body = await request.json();
  const { docID, sheetID } = body;
  const currentUser = await getCurrentUser();

  if (currentUser) {
    // find userdata in google sheet
    try {
      const data = [];

      // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
      const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: "ntu-nurse@ntu-nursing.iam.gserviceaccount.com",
        key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEuGdQVPu3EXC7\nUfqv0kaE3kMKJktHXlk/P9jv9AMfr3AYtLNthFuU5/fP/7dI/6CEE8u+fzl/DStJ\ntNdL990gFuXmDaq5wkxSFz6MuSCmNBrJG+HqAEhXUuVFEbteEsspLLGsFSGJvNn6\nE1A1/fogkut6s1kG2ANgDQ7z9zqK29uY3aRd2/zcBRa+Z1FeHXT00o0lJNCD+0If\nyEAd2yUh1VPvwrpXOu8dRbxE7o4H0iWjG6gC4fdTv5M56tsOLj5EAeXxqgt8OMFj\ncuc/oGIBAuHK82lDuYMZy9LIimDxViWHm+JQsT7REtkRcsrFfh3MAZ2yv96nYmhG\n2kJqf9CXAgMBAAECggEABsgiAlT2WzimCER/6JvOg+TIWYs5wSYcMYqunJHETHgB\n3KLYz10Rbdq+t6ml1JsWGjeMfe6+OVu83aJMYc6+Ys18nie5IQT1GJy7MqLB4Lj0\ndhvDTWE2cpGQXIc19xJIIA1DEB79Cas8YIYAl+aU6ZaRuP3XLd3jOpEjWNRxwjkD\n9cHuF6sYNL8s+KLJhCkIjxjkojYhapaN19eYBLtJXaten/gkjEvyX8jiIE7ETUL1\nNOSE4rp/idFr5H1xXxJeX59kYC9KtfOfPS3nkx2vKiTF9DOeLkjhOygthpQ5atax\nsQSz/WXIG/k39nNRxj8vct6bn70hg1AOIi9Gk3zYgQKBgQDwhmAnamy4VY7SECE8\n8wtTB2L6y+MdUq26OiUj63hkNJWBiSPtygrnpiKs7W8XBnDOWvUJ02gprjjhPalC\ncON6RHuWcG67wQj4aR9VuJFAjLTvc9Gbfpq/WQVhswFNFhXYd/wcAOSZjdkk9+bO\nJ9yEgrwQyqFJSTgqorMKqxvJNwKBgQDRYIivThjw/2TGei33OoNIg0pv7dRwG8cZ\nVtuNnmi1yjEO+2tzI8FdYhH/kgO9QMPw8bC6OE7eAKr8jUo5JqaIP4hGVkm2n/SA\n5hqG6X6Ep+eBYBgXblt6GUw393/cvnVYMqEYfHfyfZ4GoBYyX24KXHO5XA+i1sX9\nB1OfrXpjoQKBgAFBUkMiZQrZN3OVLfc5dXerdDLG2ZqPkeSE5Si409oCBD22z38w\nLLpkvY2Vd5zxJamOA/VXKxX8mMNkJPv5xtYegV6Zm5pTOY7CTa2O1wM1OMR/IDrl\ngD07Y7HM01bppJeKmMA0qPy8JsPwnz24K4htfjnANPNC9I4UZ0bI+c4lAoGBALlG\njA1ctXNk/D8p1M0GKTAchd0f/rGp0vgYRTY/a/cZ0Wmpj76WcEB7TOPzyH1K91iZ\n9sICm7+VpbjQKlMCYbEFT0i2iIojZ1A8zlJ+AifPEGwKpabuT+JuymRoDew/WUVP\noAAz/ExHXnQMazft/EkM4Jaw4WE+Xnr2ZchR0ZChAoGBAOqWDB9C6nnd7mFog9vy\nPpOVNZ1gxlAVh/rlzOC/GMqV1DPHbpK+1nliz38eab+Fn+RCZqgUKZSpB2jxhduI\n2JZLJe3KOg6qTmSD2uyAUuSBAYjU8T821Sf1Wn6cu/yldYE0BWrfat7RC18fwnaA\niG0JHiDfNY7Lkolw2LlUdqR7\n-----END PRIVATE KEY-----\n",
        scopes: ["https://www.googleapis.com/auth/spreadsheets"],
      });

      const doc = new GoogleSpreadsheet(docID, serviceAccountAuth);
      await doc.loadInfo(); // loads document properties and worksheets

      const sheet = doc.sheetsById[sheetID];
      const rows = await sheet.getRows();

      for (let row of rows) {
        data.push(row.get("3. 學號"));
      }
      // console.log(doc.title);
      // console.log(data);

      const result = data.includes(currentUser.studentId)
        ? "finish"
        : "unfinish";

      return NextResponse.json(result);
    } catch (error: any) {
      console.log(error);
    }
    return NextResponse.json("error");
  } else {
    // Return error response if no user found
    return NextResponse.json({ error: "User not found" });
  }
}
