import { NextResponse } from "next/server";
import getCurrentUser from "@/app/action/getCurrentUser";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import prisma from "@/lib/prismadb";

export async function POST(request: Request) {
  const body = await request.json();
  const { docID, sheetID } = body;
  const currentUser = await getCurrentUser();

  if (currentUser) {
    // find userdata in google sheet
    try {
      const data = [];

      // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
      const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: "ntu-nurse@ntu-nursing.iam.gserviceaccount.com",
        key: process.env.GOOGLE_PRIVATE_KEY,
        scopes: ["https://www.googleapis.com/auth/spreadsheets"],
      });

      const doc = new GoogleSpreadsheet(docID, serviceAccountAuth);
      await doc.loadInfo(); // loads document properties and worksheets

      const sheet = doc.sheetsById[sheetID];
      const rows = await sheet.getRows();

      for (let row of rows) {
        data.push(row.get("3. 學號"));
      }
      // console.log(doc.title);
      // console.log(data);

      const result = data.includes(currentUser.studentId)
        ? "finish"
        : "unfinish";

      return NextResponse.json(result);
    } catch (error: any) {
      console.log(error);
    }
    return NextResponse.json("error");
  } else {
    // Return error response if no user found
    return NextResponse.json({ error: "User not found" });
  }
}
